In [1]:
import sys
from pathlib import Path

project_root = Path().resolve().parent

# путь до src
src_path = project_root / "src"

# добавляем src в пути импорта
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

print("PROJECT ROOT:", project_root)
print("SRC PATH:", src_path)

PROJECT ROOT: C:\Users\denis\credit_scoring
SRC PATH: C:\Users\denis\credit_scoring\src

In [39]:
from config.db_config import DB_ARGS, DATA_FULL_PATH
from app.utils.db_manager import PostgresDB

db = PostgresDB(DB_ARGS)
db.connect()

Подключение к БД успешно установлено

In [3]:
import os
from datetime import datetime

import pandas as pd
import psycopg2

In [4]:
from warnings import filterwarnings

filterwarnings('ignore', category=UserWarning, message='.*pandas only supports SQLAlchemy connectable.*')

In [29]:
sql_schema_query = """
DROP TABLE IF EXISTS bureau;

CREATE TABLE bureau(
    SK_ID_CURR integer,
    SK_ID_BUREAU integer,
    CREDIT_ACTIVE varchar(13),
    CREDIT_CURRENCY varchar(15),
    DAYS_CREDIT smallint,
    CREDIT_DAY_OVERDUE smallint,
    DAYS_CREDIT_ENDDATE real,
    DAYS_ENDDATE_FACT real,
    AMT_CREDIT_MAX_OVERDUE real,
    CNT_CREDIT_PROLONG smallint,
    AMT_CREDIT_SUM real,
    AMT_CREDIT_SUM_DEBT real,
    AMT_CREDIT_SUM_LIMIT real,
    AMT_CREDIT_SUM_OVERDUE real,
    CREDIT_TYPE varchar(49),
    DAYS_CREDIT_UPDATE integer,
    AMT_ANNUITY real
);
"""

db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [30]:
from pathlib import Path

bureau_columns = [
    "SK_ID_CURR",
    "SK_ID_BUREAU",
    "CREDIT_ACTIVE",
    "CREDIT_CURRENCY",
    "DAYS_CREDIT",
    "CREDIT_DAY_OVERDUE",
    "DAYS_CREDIT_ENDDATE",
    "DAYS_ENDDATE_FACT",
    "AMT_CREDIT_MAX_OVERDUE",
    "CNT_CREDIT_PROLONG",
    "AMT_CREDIT_SUM",
    "AMT_CREDIT_SUM_DEBT",
    "AMT_CREDIT_SUM_LIMIT",
    "AMT_CREDIT_SUM_OVERDUE",
    "CREDIT_TYPE",
    "DAYS_CREDIT_UPDATE",
    "AMT_ANNUITY"
]

bureau_file = Path(DATA_FULL_PATH) / "bureau.csv"

db.copy_from_csv(
    table_name="bureau",
    file_path=str(bureau_file),
    columns=bureau_columns
)

Данные из bureau.csv успешно загружены в bureau
Время выполнения: 0:00:05

In [7]:
sql_query = """
    SELECT * FROM bureau
    LIMIT 10
"""

df = db.get_df(sql_query)
df

Время выполнения: 0:00:00

,sk_id_curr,sk_id_bureau,credit_active,credit_currency,days_credit,credit_day_overdue,days_credit_enddate,days_enddate_fact,amt_credit_max_overdue,cnt_credit_prolong,amt_credit_sum,amt_credit_sum_debt,amt_credit_sum_limit,amt_credit_sum_overdue,credit_type,days_credit_update,amt_annuity
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,0.0,Consumer credit,-131,None
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,0.0,Credit card,-20,None
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,None
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,None
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,None
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,0.0,Credit card,-31,None
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,0.0,Consumer credit,-22,None
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,0.0,Consumer credit,-1710,None
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,0.0,Consumer credit,-840,None
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,0.0,Credit card,-690,None

In [9]:
query = """
SELECT 
    sk_id_curr,
    sk_id_bureau,
    credit_active,
    credit_currency
FROM 
    bureau
"""
db.get_df(query)

Время выполнения: 0:00:02

         sk_id_curr  sk_id_bureau credit_active credit_currency
0            215354       5714462        Closed      currency 1
1            215354       5714463        Active      currency 1
2            215354       5714464        Active      currency 1
3            215354       5714465        Active      currency 1
4            215354       5714466        Active      currency 1
...             ...           ...           ...             ...
1716423      259355       5057750        Active      currency 1
1716424      100044       5057754        Closed      currency 1
1716425      100044       5057762        Closed      currency 1
1716426      246829       5057770        Closed      currency 1
1716427      246829       5057778        Closed      currency 1

[1716428 rows x 4 columns]

In [10]:
query = """
    SELECT 
        sk_id_curr AS id_loan,
        COUNT(sk_id_bureau) AS count_loans_bki_history,
        SUM(amt_credit_sum) AS loans_sum
    FROM 
        bureau
    GROUP BY 
        sk_id_curr
    LIMIT 10
"""
db.get_df(query)

Время выполнения: 0:00:00

   id_loan  count_loans_bki_history   loans_sum
0   100001                        7  1453365.00
1   100002                        8   865055.56
2   100003                        4  1017400.50
3   100004                        2   189037.80
4   100005                        3   657126.00
5   100007                        1   146250.00
6   100008                        3   468445.50
7   100009                       18  4800811.50
8   100010                        2   990000.00
9   100011                        4   435228.30

### Первичный анализ типов данных

Функция `analyze_dataframe()` выполняет автоматический анализ структуры датафрейма и формирует отчет по каждому столбцу: тип данных, количество пропусков, диапазон значений, длину текстовых полей и проверку на целочисленный формат.

In [6]:
import pandas as pd
from pathlib import Path


def analyze_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    rows = []

    for col in df.columns:
        series = df[col]
        non_null = series.dropna()

        pandas_dtype = str(series.dtype)
        null_count = int(series.isna().sum())
        unique_count = int(non_null.nunique())

        min_value = None
        max_value = None
        max_len = None
        sample_value = None
        is_integer_like = False

        if not non_null.empty:
            sample_value = non_null.iloc[0]

            if pd.api.types.is_numeric_dtype(series):
                min_value = non_null.min()
                max_value = non_null.max()

                # если float, но все значения целые по смыслу
                if pd.api.types.is_float_dtype(series):
                    is_integer_like = ((non_null % 1) == 0).all()
                elif pd.api.types.is_integer_dtype(series):
                    is_integer_like = True

            else:
                max_len = non_null.astype(str).map(len).max()

        rows.append({
            "column_name": col,
            "pandas_dtype": pandas_dtype,
            "null_count": null_count,
            "unique_count": unique_count,
            "min_value": min_value,
            "max_value": max_value,
            "max_len": max_len,
            "is_integer_like": is_integer_like,
            "sample_value": sample_value,
        })

    return pd.DataFrame(rows)

### Автоматический подбор типов данных PostgreSQL

Для автоматизации создания SQL-схемы была реализована функция `suggest_postgres_type()`.

Функция на основе результатов предварительного анализа столбцов предлагает наиболее подходящий тип данных PostgreSQL.

Логика выбора типа:

- для ключевых идентификаторов (`SK_ID_CURR`, `SK_ID_BUREAU`, `SK_ID_PREV`) всегда используется тип `INTEGER`, чтобы обеспечить единый формат связей между таблицами
- для целочисленных признаков автоматически подбирается один из типов:
  - `SMALLINT`
  - `INTEGER`
  - `BIGINT`
  
  выбор зависит от диапазона значений
- для вещественных признаков:
  - если значения по смыслу являются целыми (`12.0`, `45.0`), также подбирается целочисленный SQL-тип
  - в остальных случаях используется `REAL`
- для логических признаков используется `BOOLEAN`
- для строковых признаков используется `VARCHAR(n)`, где `n` — максимальная длина значения в столбце
- если тип определить невозможно, используется `TEXT`

In [7]:
def suggest_postgres_type(column_name: str, pandas_dtype: str, min_value, max_value, max_len, is_integer_like: bool):
    key_columns = {
        "SK_ID_CURR": "INTEGER",
        "SK_ID_BUREAU": "INTEGER",
        "SK_ID_PREV": "INTEGER",
    }

    if column_name in key_columns:
        return key_columns[column_name]

    if pandas_dtype in ["int64", "int32"]:
        if min_value is not None and max_value is not None:
            if -32768 <= min_value <= 32767 and -32768 <= max_value <= 32767:
                return "SMALLINT"
            elif -2147483648 <= min_value <= 2147483647 and -2147483648 <= max_value <= 2147483647:
                return "INTEGER"
            else:
                return "BIGINT"

    if pandas_dtype in ["float64", "float32"]:
        if is_integer_like and min_value is not None and max_value is not None:
            if -32768 <= min_value <= 32767 and -32768 <= max_value <= 32767:
                return "SMALLINT"
            elif -2147483648 <= min_value <= 2147483647 and -2147483648 <= max_value <= 2147483647:
                return "INTEGER"
            else:
                return "BIGINT"

        return "REAL"

    if pandas_dtype == "bool":
        return "BOOLEAN"

    if max_len is not None:
        return f"VARCHAR({int(max_len)})"

    return "TEXT"

### Построение отчета по типам данных

Функция `build_type_report()` формирует итоговый отчет по структуре CSV-файла: выполняет анализ столбцов и автоматически подбирает рекомендуемые типы данных PostgreSQL.

In [8]:
def build_type_report(csv_path: str, nrows: int | None = None) -> pd.DataFrame:
    df = pd.read_csv(csv_path, nrows=nrows)
    report = analyze_dataframe(df)

    report["suggested_pg_type"] = report.apply(
        lambda row: suggest_postgres_type(
            column_name=row["column_name"],
            pandas_dtype=row["pandas_dtype"],
            min_value=row["min_value"],
            max_value=row["max_value"],
            max_len=row["max_len"],
            is_integer_like=row["is_integer_like"],
        ),
        axis=1
    )

    return report

In [13]:
file_path = Path(DATA_FULL_PATH) / "previous_application.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_PREV,int64,0,100000,1.000001e+06,2.845377e+06,NaN,True,2030495,INTEGER
1,SK_ID_CURR,int64,0,79977,1.000060e+05,4.562540e+05,NaN,True,271877,INTEGER
2,NAME_CONTRACT_TYPE,object,0,4,NaN,NaN,15.0,False,Consumer loans,VARCHAR(15)
3,AMT_ANNUITY,float64,21133,52299,0.000000e+00,4.179276e+05,NaN,False,1730.43,REAL
4,AMT_APPLICATION,float64,0,21832,0.000000e+00,3.826372e+06,NaN,False,17145.0,REAL
5,AMT_CREDIT,float64,0,28993,0.000000e+00,4.104351e+06,NaN,False,17145.0,REAL
6,AMT_DOWN_PAYMENT,float64,50584,6409,0.000000e+00,1.035000e+06,NaN,False,0.0,REAL
7,AMT_GOODS_PRICE,float64,21600,21832,0.000000e+00,3.826372e+06,NaN,False,17145.0,REAL
8,WEEKDAY_APPR_PROCESS_START,object,0,7,NaN,NaN,9.0,False,SATURDAY,VARCHAR(9)
9,HOUR_APPR_PROCESS_START,int64,0,24,0.000000e+00,2.300000e+01,NaN,True,15,SMALLINT
10,FLAG_LAST_APPL_PER_CONTRACT,object,0,2,NaN,NaN,1.0,False,Y,VARCHAR(1)
11,NFLAG_LAST_APPL_IN_DAY,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
12,RATE_DOWN_PAYMENT,float64,50584,20165,0.000000e+00,9.484449e-01,NaN,False,0.0,REAL
13,RATE_INTEREST_PRIMARY,float64,99659,37,5.913521e-02,1.000000e+00,NaN,False,0.182832,REAL
14,RATE_INTEREST_PRIVILEGED,float64,99659,12,4.244186e-01,8.673362e-01,NaN,False,0.867336,REAL
15,NAME_CASH_LOAN_PURPOSE,object,0,25,NaN,NaN,32.0,False,XAP,VARCHAR(32)
16,NAME_CONTRACT_STATUS,object,0,4,NaN,NaN,12.0,False,Approved,VARCHAR(12)
17,DAYS_DECISION,int64,0,2921,-2.922000e+03,-2.000000e+00,NaN,True,-73,SMALLINT
18,NAME_PAYMENT_TYPE,object,0,4,NaN,NaN,41.0,False,Cash through the bank,VARCHAR(41)
19,CODE_REJECT_REASON,object,0,9,NaN,NaN,6.0,False,XAP,VARCHAR(6)
20,NAME_TYPE_SUITE,object,48484,7,NaN,NaN,15.0,False,Unaccompanied,VARCHAR(15)
21,NAME_CLIENT_TYPE,object,0,4,NaN,NaN,9.0,False,Repeater,VARCHAR(9)
22,NAME_GOODS_CATEGORY,object,0,26,NaN,NaN,24.0,False,Mobile,VARCHAR(24)
23,NAME_PORTFOLIO,object,0,5,NaN,NaN,5.0,False,POS,VARCHAR(5)
24,NAME_PRODUCT_TYPE,object,0,3,NaN,NaN,7.0,False,XNA,VARCHAR(7)
25,CHANNEL_TYPE,object,0,8,NaN,NaN,26.0,False,Country-wide,VARCHAR(26)
26,SELLERPLACE_AREA,int64,0,1410,-1.000000e+00,4.000000e+06,NaN,True,35,INTEGER
27,NAME_SELLER_INDUSTRY,object,0,11,NaN,NaN,20.0,False,Connectivity,VARCHAR(20)
28,CNT_PAYMENT,float64,21133,33,0.000000e+00,7.200000e+01,NaN,True,12.0,SMALLINT
29,NAME_YIELD_GROUP,object,0,5,NaN,NaN,10.0,False,middle,VARCHAR(10)
30,PRODUCT_COMBINATION,object,17,17,NaN,NaN,30.0,False,POS mobile with interest,VARCHAR(30)
31,DAYS_FIRST_DRAWING,float64,38120,1598,-2.920000e+03,3.652430e+05,NaN,True,365243.0,INTEGER
32,DAYS_FIRST_DUE,float64,38120,2891,-2.891000e+03,3.652430e+05,NaN,True,-42.0,INTEGER
33,DAYS_LAST_DUE_1ST_VERSION,float64,38120,4330,-2.800000e+03,3.652430e+05,NaN,True,300.0,INTEGER
34,DAYS_LAST_DUE,float64,38120,2804,-2.888000e+03,3.652430e+05,NaN,True,-42.0,INTEGER
35,DAYS_TERMINATION,float64,38120,2750,-2.847000e+03,3.652430e+05,NaN,True,-37.0,INTEGER
36,NFLAG_INSURED_ON_APPROVAL,float64,38120,2,0.000000e+00,1.000000e+00,NaN,True,0.0,SMALLINT

In [16]:
file_path = Path(DATA_FULL_PATH) / "POS_CASH_balance.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_PREV,int64,0,90062,1000001.0,2843487.0,NaN,True,1803195,INTEGER
1,SK_ID_CURR,int64,0,77469,100007.0,456255.0,NaN,True,182943,INTEGER
2,MONTHS_BALANCE,int64,0,93,-96.0,-1.0,NaN,True,-31,SMALLINT
3,CNT_INSTALMENT,float64,245,55,1.0,72.0,NaN,True,48.0,SMALLINT
4,CNT_INSTALMENT_FUTURE,float64,245,63,0.0,68.0,NaN,True,45.0,SMALLINT
5,NAME_CONTRACT_STATUS,object,0,6,NaN,NaN,21.0,False,Active,VARCHAR(21)
6,SK_DPD,int64,0,100,0.0,2214.0,NaN,True,0,SMALLINT
7,SK_DPD_DEF,int64,0,39,0.0,203.0,NaN,True,0,SMALLINT

In [18]:
file_path = Path(DATA_FULL_PATH) / "installments_payments.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_PREV,int64,0,71415,1000011.0,2843477.00,None,True,1054186.00,INTEGER
1,SK_ID_CURR,int64,0,48591,100003.0,199999.00,None,True,161674.00,INTEGER
2,NUM_INSTALMENT_VERSION,float64,0,33,0.0,34.00,None,True,1.00,SMALLINT
3,NUM_INSTALMENT_NUMBER,int64,0,211,1.0,237.00,None,True,6.00,SMALLINT
4,DAYS_INSTALMENT,float64,0,2921,-2922.0,-2.00,None,True,-1180.00,SMALLINT
5,DAYS_ENTRY_PAYMENT,float64,0,2948,-3026.0,-2.00,None,True,-1187.00,SMALLINT
6,AMT_INSTALMENT,float64,0,58765,0.0,2292736.86,None,False,6948.36,REAL
7,AMT_PAYMENT,float64,0,60248,0.0,2292736.86,None,False,6948.36,REAL

In [19]:
file_path = Path(DATA_FULL_PATH) / "credit_card_balance.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_PREV,int64,0,53559,1000094.000,2843477.000,NaN,True,2562384,INTEGER
1,SK_ID_CURR,int64,0,53383,100011.000,456248.000,NaN,True,378907,INTEGER
2,MONTHS_BALANCE,int64,0,96,-96.000,-1.000,NaN,True,-6,SMALLINT
3,AMT_BALANCE,float64,0,38312,-135359.010,959924.475,NaN,False,56.97,REAL
4,AMT_CREDIT_LIMIT_ACTUAL,int64,0,135,0.000,1350000.000,NaN,True,135000,INTEGER
5,AMT_DRAWINGS_ATM_CURRENT,float64,22233,430,0.000,1305000.000,NaN,False,0.0,REAL
6,AMT_DRAWINGS_CURRENT,float64,0,6246,0.000,1440180.000,NaN,False,877.5,REAL
7,AMT_DRAWINGS_OTHER_CURRENT,float64,22233,156,0.000,761940.000,NaN,False,0.0,REAL
8,AMT_DRAWINGS_POS_CURRENT,float64,22233,5603,0.000,1440180.000,NaN,False,877.5,REAL
9,AMT_INST_MIN_REGULARITY,float64,6131,12610,0.000,47251.305,NaN,False,1700.325,REAL
10,AMT_PAYMENT_CURRENT,float64,22230,16780,0.000,950814.045,NaN,False,1800.0,REAL
11,AMT_PAYMENT_TOTAL_CURRENT,float64,0,9221,0.000,948564.045,NaN,False,1800.0,REAL
12,AMT_RECEIVABLE_PRINCIPAL,float64,0,35401,-135867.105,899968.590,NaN,False,0.0,REAL
13,AMT_RECIVABLE,float64,0,39613,-133442.235,957233.475,NaN,False,0.0,REAL
14,AMT_TOTAL_RECEIVABLE,float64,0,39616,-133442.235,957233.475,NaN,False,0.0,REAL
15,CNT_DRAWINGS_ATM_CURRENT,float64,22233,26,0.000,33.000,NaN,True,0.0,SMALLINT
16,CNT_DRAWINGS_CURRENT,int64,0,79,0.000,108.000,NaN,True,1,SMALLINT
17,CNT_DRAWINGS_OTHER_CURRENT,float64,22233,6,0.000,6.000,NaN,True,0.0,SMALLINT
18,CNT_DRAWINGS_POS_CURRENT,float64,22233,76,0.000,108.000,NaN,True,1.0,SMALLINT
19,CNT_INSTALMENT_MATURE_CUM,float64,6131,115,0.000,116.000,NaN,True,35.0,SMALLINT
20,NAME_CONTRACT_STATUS,object,0,5,NaN,NaN,13.0,False,Active,VARCHAR(13)
21,SK_DPD,int64,0,285,0.000,3045.000,NaN,True,0,SMALLINT
22,SK_DPD_DEF,int64,0,37,0.000,3045.000,NaN,True,0,SMALLINT

In [20]:
file_path = Path(DATA_FULL_PATH) / "bureau_balance.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_BUREAU,int64,0,3111,5001726.0,6560309.0,NaN,True,5715448,INTEGER
1,MONTHS_BALANCE,int64,0,97,-96.0,0.0,NaN,True,0,SMALLINT
2,STATUS,object,0,8,NaN,NaN,1.0,False,C,VARCHAR(1)

In [38]:
file_path = Path(DATA_FULL_PATH) / "application_test.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_CURR,int64,0,48744,100001.000000,4.562500e+05,NaN,True,100001,INTEGER
1,NAME_CONTRACT_TYPE,object,0,2,NaN,NaN,15.0,False,Cash loans,VARCHAR(15)
2,CODE_GENDER,object,0,2,NaN,NaN,1.0,False,F,VARCHAR(1)
3,FLAG_OWN_CAR,object,0,2,NaN,NaN,1.0,False,N,VARCHAR(1)
4,FLAG_OWN_REALTY,object,0,2,NaN,NaN,1.0,False,Y,VARCHAR(1)
5,CNT_CHILDREN,int64,0,11,0.000000,2.000000e+01,NaN,True,0,SMALLINT
6,AMT_INCOME_TOTAL,float64,0,606,26941.500000,4.410000e+06,NaN,False,135000.0,REAL
7,AMT_CREDIT,float64,0,2937,45000.000000,2.245500e+06,NaN,False,568800.0,REAL
8,AMT_ANNUITY,float64,24,7491,2295.000000,1.805760e+05,NaN,False,20560.5,REAL
9,AMT_GOODS_PRICE,float64,0,677,45000.000000,2.245500e+06,NaN,False,450000.0,REAL
10,NAME_TYPE_SUITE,object,911,7,NaN,NaN,15.0,False,Unaccompanied,VARCHAR(15)
11,NAME_INCOME_TYPE,object,0,7,NaN,NaN,20.0,False,Working,VARCHAR(20)
12,NAME_EDUCATION_TYPE,object,0,5,NaN,NaN,29.0,False,Higher education,VARCHAR(29)
13,NAME_FAMILY_STATUS,object,0,5,NaN,NaN,20.0,False,Married,VARCHAR(20)
14,NAME_HOUSING_TYPE,object,0,6,NaN,NaN,19.0,False,House / apartment,VARCHAR(19)
15,REGION_POPULATION_RELATIVE,float64,0,81,0.000253,7.250800e-02,NaN,False,0.01885,REAL
16,DAYS_BIRTH,int64,0,15477,-25195.000000,-7.338000e+03,NaN,True,-19241,SMALLINT
17,DAYS_EMPLOYED,int64,0,7863,-17463.000000,3.652430e+05,NaN,True,-2329,INTEGER
18,DAYS_REGISTRATION,float64,0,12618,-23722.000000,0.000000e+00,NaN,True,-5170.0,SMALLINT
19,DAYS_ID_PUBLISH,int64,0,5880,-6348.000000,0.000000e+00,NaN,True,-812,SMALLINT
20,OWN_CAR_AGE,float64,32312,52,0.000000,7.400000e+01,NaN,True,5.0,SMALLINT
21,FLAG_MOBIL,int64,0,2,0.000000,1.000000e+00,NaN,True,1,SMALLINT
22,FLAG_EMP_PHONE,int64,0,2,0.000000,1.000000e+00,NaN,True,1,SMALLINT
23,FLAG_WORK_PHONE,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
24,FLAG_CONT_MOBILE,int64,0,2,0.000000,1.000000e+00,NaN,True,1,SMALLINT
25,FLAG_PHONE,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
26,FLAG_EMAIL,int64,0,2,0.000000,1.000000e+00,NaN,True,1,SMALLINT
27,OCCUPATION_TYPE,object,15605,18,NaN,NaN,21.0,False,Low-skill Laborers,VARCHAR(21)
28,CNT_FAM_MEMBERS,float64,0,12,1.000000,2.100000e+01,NaN,True,2.0,SMALLINT
29,REGION_RATING_CLIENT,int64,0,3,1.000000,3.000000e+00,NaN,True,2,SMALLINT
30,REGION_RATING_CLIENT_W_CITY,int64,0,4,-1.000000,3.000000e+00,NaN,True,2,SMALLINT
31,WEEKDAY_APPR_PROCESS_START,object,0,7,NaN,NaN,9.0,False,TUESDAY,VARCHAR(9)
32,HOUR_APPR_PROCESS_START,int64,0,24,0.000000,2.300000e+01,NaN,True,18,SMALLINT
33,REG_REGION_NOT_LIVE_REGION,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
34,REG_REGION_NOT_WORK_REGION,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
35,LIVE_REGION_NOT_WORK_REGION,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
36,REG_CITY_NOT_LIVE_CITY,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
37,REG_CITY_NOT_WORK_CITY,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
38,LIVE_CITY_NOT_WORK_CITY,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
39,ORGANIZATION_TYPE,object,0,58,NaN,NaN,22.0,False,Kindergarten,VARCHAR(22)
40,EXT_SOURCE_1,float64,20532,27207,0.013458,9.391445e-01,NaN,False,0.752614,REAL
41,EXT_SOURCE_2,float64,8,38885,0.000008,8.549997e-01,NaN,False,0.789654,REAL
42,EXT_SOURCE_3,float64,8668,702,0.000527,8.825303e-01,NaN,False,0.15952,REAL
43,APARTMENTS_AVG,float64,23887,1543,0.000000,1.000000e+00,NaN,False,0.066,REAL
44,BASEMENTAREA_AVG,float64,27641,2816,0.000000,1.000000e+00,NaN,False,0.059,REAL
45,YEARS_BEGINEXPLUATATION_AVG,float64,22856,175,0.000000,1.000000e+00,NaN,False,0.9732,REAL
46,YEARS_BUILD_AVG,float64,31818,130,0.000000,1.000000e+00,NaN,False,0.9592,REAL
47,COMMONAREA_AVG,float64,33495,2042,0.000000,1.000000e+00,NaN,False,0.1165,REAL
48,ELEVATORS_AVG,float64,25189,181,0.000000,1.000000e+00,NaN,False,0.32,REAL
49,ENTRANCES_AVG,float64,23579,200,0.000000,1.000000e+00,NaN,False,0.1379,REAL
50,FLOORSMAX_AVG,float64,23321,252,0.000000,1.000000e+00,NaN,False,0.125,REAL
51,FLOORSMIN_AVG,float64,32466,198,0.000000,1.000000e+00,NaN,False,0.0417,REAL
52,LANDAREA_AVG,float64,28254,2540,0.000000,1.000000e+00,NaN,False,0.2042,REAL
53,LIVINGAPARTMENTS_AVG,float64,32780,1211,0.000000,1.000000e+00,NaN,False,0.2404,REAL
54,LIVINGAREA_AVG,float64,23552,3848,0.000000,1.000000e+00,NaN,False,0.0505,REAL
55,NONLIVINGAPARTMENTS_AVG,float64,33347,241,0.000000,1.000000e+00,NaN,False,0.0386,REAL
56,NONLIVINGAREA_AVG,float64,26084,2026,0.000000,1.000000e+00,NaN,False,0.08,REAL
57,APARTMENTS_MODE,float64,23887,636,0.000000,1.000000e+00,NaN,False,0.0672,REAL
58,BASEMENTAREA_MODE,float64,27641,2835,0.000000,1.000000e+00,NaN,False,0.0612,REAL
59,YEARS_BEGINEXPLUATATION_MODE,float64,22856,160,0.000000,1.000000e+00,NaN,False,0.9732,REAL
60,YEARS_BUILD_MODE,float64,31818,132,0.000000,1.000000e+00,NaN,False,0.9608,REAL
61,COMMONAREA_MODE,float64,33495,2001,0.000000,1.000000e+00,NaN,False,0.1176,REAL
62,ELEVATORS_MODE,float64,25189,26,0.000000,1.000000e+00,NaN,False,0.3222,REAL
63,ENTRANCES_MODE,float64,23579,30,0.000000,1.000000e+00,NaN,False,0.1379,REAL
64,FLOORSMAX_MODE,float64,23321,25,0.000000,1.000000e+00,NaN,False,0.125,REAL
65,FLOORSMIN_MODE,float64,32466,25,0.000000,1.000000e+00,NaN,False,0.0417,REAL
66,LANDAREA_MODE,float64,28254,2560,0.000000,1.000000e+00,NaN,False,0.2089,REAL
67,LIVINGAPARTMENTS_MODE,float64,32780,602,0.000000,1.000000e+00,NaN,False,0.2626,REAL
68,LIVINGAREA_MODE,float64,23552,3842,0.000000,1.000000e+00,NaN,False,0.0526,REAL
69,NONLIVINGAPARTMENTS_MODE,float64,33347,106,0.000000,1.000000e+00,NaN,False,0.0389,REAL
70,NONLIVINGAREA_MODE,float64,26084,2025,0.000000,1.000000e+00,NaN,False,0.0847,REAL
71,APARTMENTS_MEDI,float64,23887,918,0.000000,1.000000e+00,NaN,False,0.0666,REAL
72,BASEMENTAREA_MEDI,float64,27641,2805,0.000000,1.000000e+00,NaN,False,0.059,REAL
73,YEARS_BEGINEXPLUATATION_MEDI,float64,22856,169,0.000000,1.000000e+00,NaN,False,0.9732,REAL
74,YEARS_BUILD_MEDI,float64,31818,129,0.000000,1.000000e+00,NaN,False,0.9597,REAL
75,COMMONAREA_MEDI,float64,33495,2034,0.000000,1.000000e+00,NaN,False,0.1173,REAL
76,ELEVATORS_MEDI,float64,25189,43,0.000000,1.000000e+00,NaN,False,0.32,REAL
77,ENTRANCES_MEDI,float64,23579,43,0.000000,1.000000e+00,NaN,False,0.1379,REAL
78,FLOORSMAX_MEDI,float64,23321,47,0.000000,1.000000e+00,NaN,False,0.125,REAL
79,FLOORSMIN_MEDI,float64,32466,44,0.000000,1.000000e+00,NaN,False,0.0417,REAL
80,LANDAREA_MEDI,float64,28254,2562,0.000000,1.000000e+00,NaN,False,0.2078,REAL
81,LIVINGAPARTMENTS_MEDI,float64,32780,843,0.000000,1.000000e+00,NaN,False,0.2446,REAL
82,LIVINGAREA_MEDI,float64,23552,3885,0.000000,1.000000e+00,NaN,False,0.0514,REAL
83,NONLIVINGAPARTMENTS_MEDI,float64,33347,134,0.000000,1.000000e+00,NaN,False,0.0388,REAL
84,NONLIVINGAREA_MEDI,float64,26084,2030,0.000000,1.000000e+00,NaN,False,0.0817,REAL
85,FONDKAPREMONT_MODE,object,32797,4,NaN,NaN,21.0,False,reg oper account,VARCHAR(21)
86,HOUSETYPE_MODE,object,23619,3,NaN,NaN,16.0,False,block of flats,VARCHAR(16)
87,TOTALAREA_MODE,float64,22624,3820,0.000000,1.000000e+00,NaN,False,0.0392,REAL
88,WALLSMATERIAL_MODE,object,23893,7,NaN,NaN,12.0,False,"Stone, brick",VARCHAR(12)
89,EMERGENCYSTATE_MODE,object,22209,2,NaN,NaN,3.0,False,No,VARCHAR(3)
90,OBS_30_CNT_SOCIAL_CIRCLE,float64,29,28,0.000000,3.540000e+02,NaN,True,0.0,SMALLINT
91,DEF_30_CNT_SOCIAL_CIRCLE,float64,29,8,0.000000,3.400000e+01,NaN,True,0.0,SMALLINT
92,OBS_60_CNT_SOCIAL_CIRCLE,float64,29,27,0.000000,3.510000e+02,NaN,True,0.0,SMALLINT
93,DEF_60_CNT_SOCIAL_CIRCLE,float64,29,7,0.000000,2.400000e+01,NaN,True,0.0,SMALLINT
94,DAYS_LAST_PHONE_CHANGE,float64,0,3579,-4361.000000,0.000000e+00,NaN,True,-1740.0,SMALLINT
95,FLAG_DOCUMENT_2,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
96,FLAG_DOCUMENT_3,int64,0,2,0.000000,1.000000e+00,NaN,True,1,SMALLINT
97,FLAG_DOCUMENT_4,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
98,FLAG_DOCUMENT_5,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
99,FLAG_DOCUMENT_6,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
100,FLAG_DOCUMENT_7,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
101,FLAG_DOCUMENT_8,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
102,FLAG_DOCUMENT_9,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
103,FLAG_DOCUMENT_10,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
104,FLAG_DOCUMENT_11,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
105,FLAG_DOCUMENT_12,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
106,FLAG_DOCUMENT_13,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
107,FLAG_DOCUMENT_14,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
108,FLAG_DOCUMENT_15,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
109,FLAG_DOCUMENT_16,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
110,FLAG_DOCUMENT_17,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
111,FLAG_DOCUMENT_18,int64,0,2,0.000000,1.000000e+00,NaN,True,0,SMALLINT
112,FLAG_DOCUMENT_19,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
113,FLAG_DOCUMENT_20,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
114,FLAG_DOCUMENT_21,int64,0,1,0.000000,0.000000e+00,NaN,True,0,SMALLINT
115,AMT_REQ_CREDIT_BUREAU_HOUR,float64,6049,3,0.000000,2.000000e+00,NaN,True,0.0,SMALLINT
116,AMT_REQ_CREDIT_BUREAU_DAY,float64,6049,3,0.000000,2.000000e+00,NaN,True,0.0,SMALLINT
117,AMT_REQ_CREDIT_BUREAU_WEEK,float64,6049,3,0.000000,2.000000e+00,NaN,True,0.0,SMALLINT
118,AMT_REQ_CREDIT_BUREAU_MON,float64,6049,7,0.000000,6.000000e+00,NaN,True,0.0,SMALLINT
119,AMT_REQ_CREDIT_BUREAU_QRT,float64,6049,8,0.000000,7.000000e+00,NaN,True,0.0,SMALLINT
120,AMT_REQ_CREDIT_BUREAU_YEAR,float64,6049,16,0.000000,1.700000e+01,NaN,True,0.0,SMALLINT

In [36]:
file_path = Path(DATA_FULL_PATH) / "application_train.csv"
report_prev = build_type_report(file_path, nrows=100000)
report_prev

,column_name,pandas_dtype,null_count,unique_count,min_value,max_value,max_len,is_integer_like,sample_value,suggested_pg_type
0,SK_ID_CURR,int64,0,100000,1.000020e+05,2.160900e+05,NaN,True,100002,INTEGER
1,TARGET,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
2,NAME_CONTRACT_TYPE,object,0,2,NaN,NaN,15.0,False,Cash loans,VARCHAR(15)
3,CODE_GENDER,object,0,3,NaN,NaN,3.0,False,M,VARCHAR(3)
4,FLAG_OWN_CAR,object,0,2,NaN,NaN,1.0,False,N,VARCHAR(1)
5,FLAG_OWN_REALTY,object,0,2,NaN,NaN,1.0,False,Y,VARCHAR(1)
6,CNT_CHILDREN,int64,0,12,0.000000e+00,1.200000e+01,NaN,True,0,SMALLINT
7,AMT_INCOME_TOTAL,float64,0,1212,2.565000e+04,1.170000e+08,NaN,False,202500.0,REAL
8,AMT_CREDIT,float64,0,4162,4.500000e+04,4.050000e+06,NaN,False,406597.5,REAL
9,AMT_ANNUITY,float64,7,10773,1.980000e+03,2.580255e+05,NaN,False,24700.5,REAL
10,AMT_GOODS_PRICE,float64,81,623,4.500000e+04,4.050000e+06,NaN,False,351000.0,REAL
11,NAME_TYPE_SUITE,object,405,7,NaN,NaN,15.0,False,Unaccompanied,VARCHAR(15)
12,NAME_INCOME_TYPE,object,0,8,NaN,NaN,20.0,False,Working,VARCHAR(20)
13,NAME_EDUCATION_TYPE,object,0,5,NaN,NaN,29.0,False,Secondary / secondary special,VARCHAR(29)
14,NAME_FAMILY_STATUS,object,0,6,NaN,NaN,20.0,False,Single / not married,VARCHAR(20)
15,NAME_HOUSING_TYPE,object,0,6,NaN,NaN,19.0,False,House / apartment,VARCHAR(19)
16,REGION_POPULATION_RELATIVE,float64,0,80,5.330000e-04,7.250800e-02,NaN,False,0.018801,REAL
17,DAYS_BIRTH,int64,0,16971,-2.520100e+04,-7.676000e+03,NaN,True,-9461,SMALLINT
18,DAYS_EMPLOYED,int64,0,9871,-1.753100e+04,3.652430e+05,NaN,True,-637,INTEGER
19,DAYS_REGISTRATION,float64,0,14101,-2.239200e+04,0.000000e+00,NaN,True,-3648.0,SMALLINT
20,DAYS_ID_PUBLISH,int64,0,5960,-6.265000e+03,0.000000e+00,NaN,True,-2120,SMALLINT
21,OWN_CAR_AGE,float64,66019,55,0.000000e+00,6.500000e+01,NaN,True,26.0,SMALLINT
22,FLAG_MOBIL,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
23,FLAG_EMP_PHONE,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
24,FLAG_WORK_PHONE,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
25,FLAG_CONT_MOBILE,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
26,FLAG_PHONE,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
27,FLAG_EMAIL,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
28,OCCUPATION_TYPE,object,31224,18,NaN,NaN,21.0,False,Laborers,VARCHAR(21)
29,CNT_FAM_MEMBERS,float64,1,12,1.000000e+00,1.400000e+01,NaN,True,1.0,SMALLINT
30,REGION_RATING_CLIENT,int64,0,3,1.000000e+00,3.000000e+00,NaN,True,2,SMALLINT
31,REGION_RATING_CLIENT_W_CITY,int64,0,3,1.000000e+00,3.000000e+00,NaN,True,2,SMALLINT
32,WEEKDAY_APPR_PROCESS_START,object,0,7,NaN,NaN,9.0,False,WEDNESDAY,VARCHAR(9)
33,HOUR_APPR_PROCESS_START,int64,0,24,0.000000e+00,2.300000e+01,NaN,True,10,SMALLINT
34,REG_REGION_NOT_LIVE_REGION,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
35,REG_REGION_NOT_WORK_REGION,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
36,LIVE_REGION_NOT_WORK_REGION,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
37,REG_CITY_NOT_LIVE_CITY,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
38,REG_CITY_NOT_WORK_CITY,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
39,LIVE_CITY_NOT_WORK_CITY,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
40,ORGANIZATION_TYPE,object,0,58,NaN,NaN,22.0,False,Business Entity Type 3,VARCHAR(22)
41,EXT_SOURCE_1,float64,56283,41488,1.456813e-02,9.516240e-01,NaN,False,0.083037,REAL
42,EXT_SOURCE_2,float64,215,65758,8.173617e-08,8.549997e-01,NaN,False,0.262949,REAL
43,EXT_SOURCE_3,float64,19827,765,5.272652e-04,8.960095e-01,NaN,False,0.139376,REAL
44,APARTMENTS_AVG,float64,50682,1848,0.000000e+00,1.000000e+00,NaN,False,0.0247,REAL
45,BASEMENTAREA_AVG,float64,58360,3211,0.000000e+00,1.000000e+00,NaN,False,0.0369,REAL
46,YEARS_BEGINEXPLUATATION_AVG,float64,48701,220,0.000000e+00,1.000000e+00,NaN,False,0.9722,REAL
47,YEARS_BUILD_AVG,float64,66346,142,0.000000e+00,1.000000e+00,NaN,False,0.6192,REAL
48,COMMONAREA_AVG,float64,69732,2444,0.000000e+00,1.000000e+00,NaN,False,0.0143,REAL
49,ELEVATORS_AVG,float64,53300,207,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
50,ENTRANCES_AVG,float64,50281,232,0.000000e+00,1.000000e+00,NaN,False,0.069,REAL
51,FLOORSMAX_AVG,float64,49688,300,0.000000e+00,1.000000e+00,NaN,False,0.0833,REAL
52,FLOORSMIN_AVG,float64,67702,229,0.000000e+00,1.000000e+00,NaN,False,0.125,REAL
53,LANDAREA_AVG,float64,59250,2933,0.000000e+00,1.000000e+00,NaN,False,0.0369,REAL
54,LIVINGAPARTMENTS_AVG,float64,68265,1456,0.000000e+00,1.000000e+00,NaN,False,0.0202,REAL
55,LIVINGAREA_AVG,float64,50151,4353,0.000000e+00,1.000000e+00,NaN,False,0.019,REAL
56,NONLIVINGAPARTMENTS_AVG,float64,69275,287,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
57,NONLIVINGAREA_AVG,float64,55070,2487,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
58,APARTMENTS_MODE,float64,50682,681,0.000000e+00,1.000000e+00,NaN,False,0.0252,REAL
59,BASEMENTAREA_MODE,float64,58360,3267,0.000000e+00,1.000000e+00,NaN,False,0.0383,REAL
60,YEARS_BEGINEXPLUATATION_MODE,float64,48701,187,0.000000e+00,1.000000e+00,NaN,False,0.9722,REAL
61,YEARS_BUILD_MODE,float64,66346,144,0.000000e+00,1.000000e+00,NaN,False,0.6341,REAL
62,COMMONAREA_MODE,float64,69732,2383,0.000000e+00,1.000000e+00,NaN,False,0.0144,REAL
63,ELEVATORS_MODE,float64,53300,26,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
64,ENTRANCES_MODE,float64,50281,30,0.000000e+00,1.000000e+00,NaN,False,0.069,REAL
65,FLOORSMAX_MODE,float64,49688,25,0.000000e+00,1.000000e+00,NaN,False,0.0833,REAL
66,FLOORSMIN_MODE,float64,67702,24,0.000000e+00,1.000000e+00,NaN,False,0.125,REAL
67,LANDAREA_MODE,float64,59250,2943,0.000000e+00,1.000000e+00,NaN,False,0.0377,REAL
68,LIVINGAPARTMENTS_MODE,float64,68265,644,0.000000e+00,1.000000e+00,NaN,False,0.022,REAL
69,LIVINGAREA_MODE,float64,50151,4422,0.000000e+00,1.000000e+00,NaN,False,0.0198,REAL
70,NONLIVINGAPARTMENTS_MODE,float64,69275,122,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
71,NONLIVINGAREA_MODE,float64,55070,2511,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
72,APARTMENTS_MEDI,float64,50682,1002,0.000000e+00,1.000000e+00,NaN,False,0.025,REAL
73,BASEMENTAREA_MEDI,float64,58360,3206,0.000000e+00,1.000000e+00,NaN,False,0.0369,REAL
74,YEARS_BEGINEXPLUATATION_MEDI,float64,48701,196,0.000000e+00,1.000000e+00,NaN,False,0.9722,REAL
75,YEARS_BUILD_MEDI,float64,66346,141,0.000000e+00,1.000000e+00,NaN,False,0.6243,REAL
76,COMMONAREA_MEDI,float64,69732,2454,0.000000e+00,1.000000e+00,NaN,False,0.0144,REAL
77,ELEVATORS_MEDI,float64,53300,45,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
78,ENTRANCES_MEDI,float64,50281,46,0.000000e+00,1.000000e+00,NaN,False,0.069,REAL
79,FLOORSMAX_MEDI,float64,49688,48,0.000000e+00,1.000000e+00,NaN,False,0.0833,REAL
80,FLOORSMIN_MEDI,float64,67702,46,0.000000e+00,1.000000e+00,NaN,False,0.125,REAL
81,LANDAREA_MEDI,float64,59250,2956,0.000000e+00,1.000000e+00,NaN,False,0.0375,REAL
82,LIVINGAPARTMENTS_MEDI,float64,68265,947,0.000000e+00,1.000000e+00,NaN,False,0.0205,REAL
83,LIVINGAREA_MEDI,float64,50151,4431,0.000000e+00,1.000000e+00,NaN,False,0.0193,REAL
84,NONLIVINGAPARTMENTS_MEDI,float64,69275,159,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
85,NONLIVINGAREA_MEDI,float64,55070,2520,0.000000e+00,1.000000e+00,NaN,False,0.0,REAL
86,FONDKAPREMONT_MODE,object,68218,4,NaN,NaN,21.0,False,reg oper account,VARCHAR(21)
87,HOUSETYPE_MODE,object,50105,3,NaN,NaN,16.0,False,block of flats,VARCHAR(16)
88,TOTALAREA_MODE,float64,48223,4347,0.000000e+00,1.000000e+00,NaN,False,0.0149,REAL
89,WALLSMATERIAL_MODE,object,50765,7,NaN,NaN,12.0,False,"Stone, brick",VARCHAR(12)
90,EMERGENCYSTATE_MODE,object,47333,2,NaN,NaN,3.0,False,No,VARCHAR(3)
91,OBS_30_CNT_SOCIAL_CIRCLE,float64,327,31,0.000000e+00,4.700000e+01,NaN,True,2.0,SMALLINT
92,DEF_30_CNT_SOCIAL_CIRCLE,float64,327,7,0.000000e+00,6.000000e+00,NaN,True,2.0,SMALLINT
93,OBS_60_CNT_SOCIAL_CIRCLE,float64,327,30,0.000000e+00,4.700000e+01,NaN,True,2.0,SMALLINT
94,DEF_60_CNT_SOCIAL_CIRCLE,float64,327,6,0.000000e+00,5.000000e+00,NaN,True,2.0,SMALLINT
95,DAYS_LAST_PHONE_CHANGE,float64,1,3560,-4.078000e+03,0.000000e+00,NaN,True,-1134.0,SMALLINT
96,FLAG_DOCUMENT_2,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
97,FLAG_DOCUMENT_3,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,1,SMALLINT
98,FLAG_DOCUMENT_4,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
99,FLAG_DOCUMENT_5,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
100,FLAG_DOCUMENT_6,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
101,FLAG_DOCUMENT_7,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
102,FLAG_DOCUMENT_8,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
103,FLAG_DOCUMENT_9,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
104,FLAG_DOCUMENT_10,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
105,FLAG_DOCUMENT_11,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
106,FLAG_DOCUMENT_12,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
107,FLAG_DOCUMENT_13,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
108,FLAG_DOCUMENT_14,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
109,FLAG_DOCUMENT_15,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
110,FLAG_DOCUMENT_16,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
111,FLAG_DOCUMENT_17,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
112,FLAG_DOCUMENT_18,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
113,FLAG_DOCUMENT_19,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
114,FLAG_DOCUMENT_20,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
115,FLAG_DOCUMENT_21,int64,0,2,0.000000e+00,1.000000e+00,NaN,True,0,SMALLINT
116,AMT_REQ_CREDIT_BUREAU_HOUR,float64,13437,4,0.000000e+00,3.000000e+00,NaN,True,0.0,SMALLINT
117,AMT_REQ_CREDIT_BUREAU_DAY,float64,13437,7,0.000000e+00,6.000000e+00,NaN,True,0.0,SMALLINT
118,AMT_REQ_CREDIT_BUREAU_WEEK,float64,13437,8,0.000000e+00,8.000000e+00,NaN,True,0.0,SMALLINT
119,AMT_REQ_CREDIT_BUREAU_MON,float64,13437,22,0.000000e+00,2.400000e+01,NaN,True,0.0,SMALLINT
120,AMT_REQ_CREDIT_BUREAU_QRT,float64,13437,9,0.000000e+00,8.000000e+00,NaN,True,0.0,SMALLINT
121,AMT_REQ_CREDIT_BUREAU_YEAR,float64,13437,21,0.000000e+00,2.500000e+01,NaN,True,1.0,SMALLINT

### Обоснование выбора типов для таблицы `bureau_balance`


`SK_ID_BUREAU` сохранён как `INTEGER`, так как это идентификатор записи бюро, который используется для связи с таблицей `bureau`. Тип согласован с уже созданной таблицей `bureau`, где поле `SK_ID_BUREAU` также имеет тип `INTEGER`.

`MONTHS_BALANCE` сохранён как `SMALLINT`, поскольку столбец содержит только целые значения в диапазоне от `-96` до `0`, что полностью помещается в диапазон `SMALLINT`.

`STATUS` сохранён как `VARCHAR(1)`, так как это категориальный признак, представленный строками длиной 1 символ.

In [9]:
sql_schema_query = """
DROP TABLE IF EXISTS bureau_balance;

CREATE TABLE bureau_balance (
    SK_ID_BUREAU INTEGER,
    MONTHS_BALANCE SMALLINT,
    STATUS VARCHAR(1)
);
"""

db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [10]:


bureau_balance_columns = [
    "SK_ID_BUREAU",
    "MONTHS_BALANCE",
    "STATUS"
]

bureau_balance_file = Path(DATA_FULL_PATH) / "bureau_balance.csv"

db.copy_from_csv(
    table_name="bureau_balance",
    file_path=str(bureau_balance_file),
    columns=bureau_balance_columns
)

Данные из bureau_balance.csv успешно загружены в bureau_balance
Время выполнения: 0:00:17

In [8]:
db.get_df("SELECT * FROM bureau_balance LIMIT 10;")

Время выполнения: 0:00:00

   sk_id_bureau  months_balance status
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C
5       5715448              -5      C
6       5715448              -6      C
7       5715448              -7      C
8       5715448              -8      C
9       5715448              -9      0

In [11]:
sql_schema_query = """
DROP TABLE IF EXISTS previous_application;

CREATE TABLE previous_application(
    SK_ID_PREV INTEGER,
    SK_ID_CURR INTEGER,
    NAME_CONTRACT_TYPE VARCHAR(15),
    AMT_ANNUITY REAL,
    AMT_APPLICATION REAL,
    AMT_CREDIT REAL,
    AMT_DOWN_PAYMENT REAL,
    AMT_GOODS_PRICE REAL,
    WEEKDAY_APPR_PROCESS_START VARCHAR(9),
    HOUR_APPR_PROCESS_START SMALLINT,
    FLAG_LAST_APPL_PER_CONTRACT VARCHAR(1),
    NFLAG_LAST_APPL_IN_DAY SMALLINT,
    RATE_DOWN_PAYMENT REAL,
    RATE_INTEREST_PRIMARY REAL,
    RATE_INTEREST_PRIVILEGED REAL,
    NAME_CASH_LOAN_PURPOSE VARCHAR(32),
    NAME_CONTRACT_STATUS VARCHAR(12),
    DAYS_DECISION SMALLINT,
    NAME_PAYMENT_TYPE VARCHAR(41),
    CODE_REJECT_REASON VARCHAR(6),
    NAME_TYPE_SUITE VARCHAR(15),
    NAME_CLIENT_TYPE VARCHAR(9),
    NAME_GOODS_CATEGORY VARCHAR(24),
    NAME_PORTFOLIO VARCHAR(5),
    NAME_PRODUCT_TYPE VARCHAR(7),
    CHANNEL_TYPE VARCHAR(26),
    SELLERPLACE_AREA INTEGER,
    NAME_SELLER_INDUSTRY VARCHAR(20),
    CNT_PAYMENT REAL,
    NAME_YIELD_GROUP VARCHAR(10),
    PRODUCT_COMBINATION VARCHAR(30),
    DAYS_FIRST_DRAWING REAL,
    DAYS_FIRST_DUE REAL,
    DAYS_LAST_DUE_1ST_VERSION REAL,
    DAYS_LAST_DUE REAL,
    DAYS_TERMINATION REAL,
    NFLAG_INSURED_ON_APPROVAL REAL
);
"""
db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [12]:
previous_application_columns = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "NAME_CONTRACT_TYPE",
    "AMT_ANNUITY",
    "AMT_APPLICATION",
    "AMT_CREDIT",
    "AMT_DOWN_PAYMENT",
    "AMT_GOODS_PRICE",
    "WEEKDAY_APPR_PROCESS_START",
    "HOUR_APPR_PROCESS_START",
    "FLAG_LAST_APPL_PER_CONTRACT",
    "NFLAG_LAST_APPL_IN_DAY",
    "RATE_DOWN_PAYMENT",
    "RATE_INTEREST_PRIMARY",
    "RATE_INTEREST_PRIVILEGED",
    "NAME_CASH_LOAN_PURPOSE",
    "NAME_CONTRACT_STATUS",
    "DAYS_DECISION",
    "NAME_PAYMENT_TYPE",
    "CODE_REJECT_REASON",
    "NAME_TYPE_SUITE",
    "NAME_CLIENT_TYPE",
    "NAME_GOODS_CATEGORY",
    "NAME_PORTFOLIO",
    "NAME_PRODUCT_TYPE",
    "CHANNEL_TYPE",
    "SELLERPLACE_AREA",
    "NAME_SELLER_INDUSTRY",
    "CNT_PAYMENT",
    "NAME_YIELD_GROUP",
    "PRODUCT_COMBINATION",
    "DAYS_FIRST_DRAWING",
    "DAYS_FIRST_DUE",
    "DAYS_LAST_DUE_1ST_VERSION",
    "DAYS_LAST_DUE",
    "DAYS_TERMINATION",
    "NFLAG_INSURED_ON_APPROVAL"
]
from pathlib import Path

previous_application_file = Path(DATA_FULL_PATH) / "previous_application.csv"

db.copy_from_csv(
    table_name="previous_application",
    file_path=str(previous_application_file),
    columns=previous_application_columns
)

Данные из previous_application.csv успешно загружены в previous_application
Время выполнения: 0:00:12

### Комментарий по выбору типов при загрузке `previous_application`

Для таблицы `previous_application` при прямой загрузке CSV через `COPY` часть столбцов была сохранена как `REAL`, хотя по смыслу некоторые из них являются целочисленными признаками (`CNT_PAYMENT`, `DAYS_FIRST_DRAWING`, `DAYS_FIRST_DUE`, `DAYS_LAST_DUE`, `DAYS_TERMINATION`, `NFLAG_INSURED_ON_APPROVAL`).

Это связано с тем, что в исходном CSV-файле такие значения записаны в формате с десятичной точкой, например `12.0` или `-42.0`. PostgreSQL не может напрямую загрузить такие значения в столбцы типа `SMALLINT` или `INTEGER` через `COPY`.

Поэтому на этапе первичной загрузки данных был выбран тип `REAL`, соответствующий физическому формату данных в CSV. При этом по смыслу эти признаки могут рассматриваться как целочисленные и при необходимости быть приведены к целочисленному типу на последующих этапах обработки данных.

In [13]:
sql_schema_query = """
DROP TABLE IF EXISTS pos_cash_balance;

CREATE TABLE pos_cash_balance(
    SK_ID_PREV INTEGER,
    SK_ID_CURR INTEGER,
    MONTHS_BALANCE SMALLINT,
    CNT_INSTALMENT REAL,
    CNT_INSTALMENT_FUTURE REAL,
    NAME_CONTRACT_STATUS VARCHAR(21),
    SK_DPD SMALLINT,
    SK_DPD_DEF SMALLINT
);
"""
db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [14]:
pos_cash_balance_columns = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "MONTHS_BALANCE",
    "CNT_INSTALMENT",
    "CNT_INSTALMENT_FUTURE",
    "NAME_CONTRACT_STATUS",
    "SK_DPD",
    "SK_DPD_DEF"
]
from pathlib import Path

pos_cash_balance_file = Path(DATA_FULL_PATH) / "POS_CASH_balance.csv"

db.copy_from_csv(
    table_name="pos_cash_balance",
    file_path=str(pos_cash_balance_file),
    columns=pos_cash_balance_columns
)

Данные из POS_CASH_balance.csv успешно загружены в pos_cash_balance
Время выполнения: 0:00:17

In [26]:
db.get_df("SELECT * FROM pos_cash_balance LIMIT 10;")

Время выполнения: 0:00:00

,sk_id_prev,sk_id_curr,months_balance,cnt_instalment,cnt_instalment_future,name_contract_status,sk_dpd,sk_dpd_def
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
5,2207092,342166,-32,12.0,12.0,Active,0,0
6,1110516,204376,-38,48.0,43.0,Active,0,0
7,1387235,153211,-35,36.0,36.0,Active,0,0
8,1220500,112740,-31,12.0,12.0,Active,0,0
9,2371489,274851,-32,24.0,16.0,Active,0,0

### Обоснование выбора типов для таблицы `pos_cash_balance`


Поля `SK_ID_PREV` и `SK_ID_CURR` сохранены как `INTEGER`, так как это идентификаторы, используемые для связи с другими таблицами. Типы согласованы с уже созданными таблицами `previous_application`, `bureau` и другими таблицами проекта.

Поле `MONTHS_BALANCE` сохранено как `SMALLINT`, поскольку содержит целые значения в небольшом диапазоне от `-96` до `-1`.

Поля `CNT_INSTALMENT` и `CNT_INSTALMENT_FUTURE` по смыслу являются счетчиками и могли бы быть сохранены как целочисленные типы. Однако в исходном CSV-файле они представлены как значения формата `48.0`, `45.0`, то есть как числа с плавающей точкой. Поэтому для корректной прямой загрузки через `COPY` эти поля сохранены как `REAL`.

Поле `NAME_CONTRACT_STATUS` сохранено как `VARCHAR(21)`, так как это категориальный строковый признак, а максимальная длина значения в столбце составляет 21 символ.

Поля `SK_DPD` и `SK_DPD_DEF` сохранены как `SMALLINT`, поскольку содержат небольшие целочисленные значения и не имеют пропусков.

In [15]:
sql_schema_query = """
DROP TABLE IF EXISTS installments_payments;

CREATE TABLE installments_payments(
    SK_ID_PREV INTEGER,
    SK_ID_CURR INTEGER,
    NUM_INSTALMENT_VERSION REAL,
    NUM_INSTALMENT_NUMBER SMALLINT,
    DAYS_INSTALMENT REAL,
    DAYS_ENTRY_PAYMENT REAL,
    AMT_INSTALMENT REAL,
    AMT_PAYMENT REAL
);
"""
db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [16]:
installments_payments_columns = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "NUM_INSTALMENT_VERSION",
    "NUM_INSTALMENT_NUMBER",
    "DAYS_INSTALMENT",
    "DAYS_ENTRY_PAYMENT",
    "AMT_INSTALMENT",
    "AMT_PAYMENT"
]
from pathlib import Path

installments_payments_file = Path(DATA_FULL_PATH) / "installments_payments.csv"

db.copy_from_csv(
    table_name="installments_payments",
    file_path=str(installments_payments_file),
    columns=installments_payments_columns
)

Данные из installments_payments.csv успешно загружены в installments_payments
Время выполнения: 0:00:26

### Обоснование выбора типов для таблицы `installments_payments`


Поля `SK_ID_PREV` и `SK_ID_CURR` сохранены как `INTEGER`, так как это идентификаторы, используемые для связи с другими таблицами. Типы согласованы с ранее созданными таблицами.

Поле `NUM_INSTALMENT_NUMBER` сохранено как `SMALLINT`, поскольку содержит небольшие целочисленные значения в диапазоне от 1 до 237.

Поля `NUM_INSTALMENT_VERSION`, `DAYS_INSTALMENT` и `DAYS_ENTRY_PAYMENT` по смыслу являются целочисленными признаками, однако в исходном CSV-файле они представлены в формате чисел с плавающей точкой, например `1.0` или `-1180.0`. Поэтому для корректной прямой загрузки данных через `COPY` эти поля сохранены как `REAL`.

Поля `AMT_INSTALMENT` и `AMT_PAYMENT` сохранены как `REAL`, поскольку содержат вещественные значения денежных сумм.

In [17]:
sql_schema_query = """
DROP TABLE IF EXISTS credit_card_balance;

CREATE TABLE credit_card_balance(
    SK_ID_PREV INTEGER,
    SK_ID_CURR INTEGER,
    MONTHS_BALANCE SMALLINT,
    AMT_BALANCE REAL,
    AMT_CREDIT_LIMIT_ACTUAL INTEGER,
    AMT_DRAWINGS_ATM_CURRENT REAL,
    AMT_DRAWINGS_CURRENT REAL,
    AMT_DRAWINGS_OTHER_CURRENT REAL,
    AMT_DRAWINGS_POS_CURRENT REAL,
    AMT_INST_MIN_REGULARITY REAL,
    AMT_PAYMENT_CURRENT REAL,
    AMT_PAYMENT_TOTAL_CURRENT REAL,
    AMT_RECEIVABLE_PRINCIPAL REAL,
    AMT_RECIVABLE REAL,
    AMT_TOTAL_RECEIVABLE REAL,
    CNT_DRAWINGS_ATM_CURRENT REAL,
    CNT_DRAWINGS_CURRENT SMALLINT,
    CNT_DRAWINGS_OTHER_CURRENT REAL,
    CNT_DRAWINGS_POS_CURRENT REAL,
    CNT_INSTALMENT_MATURE_CUM REAL,
    NAME_CONTRACT_STATUS VARCHAR(13),
    SK_DPD SMALLINT,
    SK_DPD_DEF SMALLINT
);
"""
db.execute_query(sql_schema_query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [18]:
credit_card_balance_columns = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "MONTHS_BALANCE",
    "AMT_BALANCE",
    "AMT_CREDIT_LIMIT_ACTUAL",
    "AMT_DRAWINGS_ATM_CURRENT",
    "AMT_DRAWINGS_CURRENT",
    "AMT_DRAWINGS_OTHER_CURRENT",
    "AMT_DRAWINGS_POS_CURRENT",
    "AMT_INST_MIN_REGULARITY",
    "AMT_PAYMENT_CURRENT",
    "AMT_PAYMENT_TOTAL_CURRENT",
    "AMT_RECEIVABLE_PRINCIPAL",
    "AMT_RECIVABLE",
    "AMT_TOTAL_RECEIVABLE",
    "CNT_DRAWINGS_ATM_CURRENT",
    "CNT_DRAWINGS_CURRENT",
    "CNT_DRAWINGS_OTHER_CURRENT",
    "CNT_DRAWINGS_POS_CURRENT",
    "CNT_INSTALMENT_MATURE_CUM",
    "NAME_CONTRACT_STATUS",
    "SK_DPD",
    "SK_DPD_DEF"
]

from pathlib import Path

credit_card_balance_file = Path(DATA_FULL_PATH) / "credit_card_balance.csv"

db.copy_from_csv(
    table_name="credit_card_balance",
    file_path=str(credit_card_balance_file),
    columns=credit_card_balance_columns
)

Данные из credit_card_balance.csv успешно загружены в credit_card_balance
Время выполнения: 0:00:16

### Обоснование выбора типов для таблицы `credit_card_balance`


Поля `SK_ID_PREV` и `SK_ID_CURR` сохранены как `INTEGER`, поскольку это идентификаторы, используемые для связи с другими таблицами. Типы согласованы с уже загруженными таблицами проекта.

Поле `MONTHS_BALANCE` сохранено как `SMALLINT`, так как содержит небольшие целочисленные значения в диапазоне от `-96` до `-1`.

Поле `AMT_CREDIT_LIMIT_ACTUAL` сохранено как `INTEGER`, поскольку это целочисленный денежный лимит без пропусков и без дробной части.

Поля `AMT_*` сохранены как `REAL`, так как содержат вещественные денежные значения.

Поля `CNT_DRAWINGS_ATM_CURRENT`, `CNT_DRAWINGS_OTHER_CURRENT`, `CNT_DRAWINGS_POS_CURRENT`, `CNT_INSTALMENT_MATURE_CUM` по смыслу являются счетчиками, однако в исходном CSV представлены как числа с плавающей точкой (`0.0`, `1.0`, `35.0`). Поэтому для корректной прямой загрузки через `COPY` они сохранены как `REAL`.

Поле `CNT_DRAWINGS_CURRENT` сохранено как `SMALLINT`, так как в исходном файле оно имеет целочисленный тип и небольшой диапазон значений.

Поле `NAME_CONTRACT_STATUS` сохранено как `VARCHAR(13)`, поскольку это категориальный строковый признак, а максимальная длина значения в столбце составляет 13 символов.

Поля `SK_DPD` и `SK_DPD_DEF` сохранены как `SMALLINT`, поскольку содержат небольшие целочисленные значения без пропусков.

In [19]:
application_column_types = {
    "SK_ID_CURR": "INTEGER",
    "TARGET": "SMALLINT",
    "NAME_CONTRACT_TYPE": "VARCHAR(15)",
    "CODE_GENDER": "VARCHAR(3)",
    "FLAG_OWN_CAR": "VARCHAR(1)",
    "FLAG_OWN_REALTY": "VARCHAR(1)",
    "CNT_CHILDREN": "SMALLINT",
    "AMT_INCOME_TOTAL": "REAL",
    "AMT_CREDIT": "REAL",
    "AMT_ANNUITY": "REAL",
    "AMT_GOODS_PRICE": "REAL",
    "NAME_TYPE_SUITE": "VARCHAR(15)",
    "NAME_INCOME_TYPE": "VARCHAR(20)",
    "NAME_EDUCATION_TYPE": "VARCHAR(29)",
    "NAME_FAMILY_STATUS": "VARCHAR(20)",
    "NAME_HOUSING_TYPE": "VARCHAR(19)",
    "REGION_POPULATION_RELATIVE": "REAL",
    "DAYS_BIRTH": "SMALLINT",
    "DAYS_EMPLOYED": "INTEGER",
    "DAYS_REGISTRATION": "REAL",
    "DAYS_ID_PUBLISH": "SMALLINT",
    "OWN_CAR_AGE": "REAL",
    "FLAG_MOBIL": "SMALLINT",
    "FLAG_EMP_PHONE": "SMALLINT",
    "FLAG_WORK_PHONE": "SMALLINT",
    "FLAG_CONT_MOBILE": "SMALLINT",
    "FLAG_PHONE": "SMALLINT",
    "FLAG_EMAIL": "SMALLINT",
    "OCCUPATION_TYPE": "VARCHAR(21)",
    "CNT_FAM_MEMBERS": "REAL",
    "REGION_RATING_CLIENT": "SMALLINT",
    "REGION_RATING_CLIENT_W_CITY": "SMALLINT",
    "WEEKDAY_APPR_PROCESS_START": "VARCHAR(9)",
    "HOUR_APPR_PROCESS_START": "SMALLINT",
    "REG_REGION_NOT_LIVE_REGION": "SMALLINT",
    "REG_REGION_NOT_WORK_REGION": "SMALLINT",
    "LIVE_REGION_NOT_WORK_REGION": "SMALLINT",
    "REG_CITY_NOT_LIVE_CITY": "SMALLINT",
    "REG_CITY_NOT_WORK_CITY": "SMALLINT",
    "LIVE_CITY_NOT_WORK_CITY": "SMALLINT",
    "ORGANIZATION_TYPE": "VARCHAR(22)",
    "EXT_SOURCE_1": "REAL",
    "EXT_SOURCE_2": "REAL",
    "EXT_SOURCE_3": "REAL",
    "APARTMENTS_AVG": "REAL",
    "BASEMENTAREA_AVG": "REAL",
    "YEARS_BEGINEXPLUATATION_AVG": "REAL",
    "YEARS_BUILD_AVG": "REAL",
    "COMMONAREA_AVG": "REAL",
    "ELEVATORS_AVG": "REAL",
    "ENTRANCES_AVG": "REAL",
    "FLOORSMAX_AVG": "REAL",
    "FLOORSMIN_AVG": "REAL",
    "LANDAREA_AVG": "REAL",
    "LIVINGAPARTMENTS_AVG": "REAL",
    "LIVINGAREA_AVG": "REAL",
    "NONLIVINGAPARTMENTS_AVG": "REAL",
    "NONLIVINGAREA_AVG": "REAL",
    "APARTMENTS_MODE": "REAL",
    "BASEMENTAREA_MODE": "REAL",
    "YEARS_BEGINEXPLUATATION_MODE": "REAL",
    "YEARS_BUILD_MODE": "REAL",
    "COMMONAREA_MODE": "REAL",
    "ELEVATORS_MODE": "REAL",
    "ENTRANCES_MODE": "REAL",
    "FLOORSMAX_MODE": "REAL",
    "FLOORSMIN_MODE": "REAL",
    "LANDAREA_MODE": "REAL",
    "LIVINGAPARTMENTS_MODE": "REAL",
    "LIVINGAREA_MODE": "REAL",
    "NONLIVINGAPARTMENTS_MODE": "REAL",
    "NONLIVINGAREA_MODE": "REAL",
    "APARTMENTS_MEDI": "REAL",
    "BASEMENTAREA_MEDI": "REAL",
    "YEARS_BEGINEXPLUATATION_MEDI": "REAL",
    "YEARS_BUILD_MEDI": "REAL",
    "COMMONAREA_MEDI": "REAL",
    "ELEVATORS_MEDI": "REAL",
    "ENTRANCES_MEDI": "REAL",
    "FLOORSMAX_MEDI": "REAL",
    "FLOORSMIN_MEDI": "REAL",
    "LANDAREA_MEDI": "REAL",
    "LIVINGAPARTMENTS_MEDI": "REAL",
    "LIVINGAREA_MEDI": "REAL",
    "NONLIVINGAPARTMENTS_MEDI": "REAL",
    "NONLIVINGAREA_MEDI": "REAL",
    "FONDKAPREMONT_MODE": "VARCHAR(21)",
    "HOUSETYPE_MODE": "VARCHAR(16)",
    "TOTALAREA_MODE": "REAL",
    "WALLSMATERIAL_MODE": "VARCHAR(12)",
    "EMERGENCYSTATE_MODE": "VARCHAR(3)",
    "OBS_30_CNT_SOCIAL_CIRCLE": "REAL",
    "DEF_30_CNT_SOCIAL_CIRCLE": "REAL",
    "OBS_60_CNT_SOCIAL_CIRCLE": "REAL",
    "DEF_60_CNT_SOCIAL_CIRCLE": "REAL",
    "DAYS_LAST_PHONE_CHANGE": "REAL",
    "FLAG_DOCUMENT_2": "SMALLINT",
    "FLAG_DOCUMENT_3": "SMALLINT",
    "FLAG_DOCUMENT_4": "SMALLINT",
    "FLAG_DOCUMENT_5": "SMALLINT",
    "FLAG_DOCUMENT_6": "SMALLINT",
    "FLAG_DOCUMENT_7": "SMALLINT",
    "FLAG_DOCUMENT_8": "SMALLINT",
    "FLAG_DOCUMENT_9": "SMALLINT",
    "FLAG_DOCUMENT_10": "SMALLINT",
    "FLAG_DOCUMENT_11": "SMALLINT",
    "FLAG_DOCUMENT_12": "SMALLINT",
    "FLAG_DOCUMENT_13": "SMALLINT",
    "FLAG_DOCUMENT_14": "SMALLINT",
    "FLAG_DOCUMENT_15": "SMALLINT",
    "FLAG_DOCUMENT_16": "SMALLINT",
    "FLAG_DOCUMENT_17": "SMALLINT",
    "FLAG_DOCUMENT_18": "SMALLINT",
    "FLAG_DOCUMENT_19": "SMALLINT",
    "FLAG_DOCUMENT_20": "SMALLINT",
    "FLAG_DOCUMENT_21": "SMALLINT",
    "AMT_REQ_CREDIT_BUREAU_HOUR": "REAL",
    "AMT_REQ_CREDIT_BUREAU_DAY": "REAL",
    "AMT_REQ_CREDIT_BUREAU_WEEK": "REAL",
    "AMT_REQ_CREDIT_BUREAU_MON": "REAL",
    "AMT_REQ_CREDIT_BUREAU_QRT": "REAL",
    "AMT_REQ_CREDIT_BUREAU_YEAR": "REAL",
    "DATASET_SOURCE": "VARCHAR(5)"
}

In [20]:
def generate_create_table_sql(table_name: str, columns_with_types: dict[str, str]) -> str:
    columns_sql = ",\n    ".join(
        [f"{col} {col_type}" for col, col_type in columns_with_types.items()]
    )

    return f"""
DROP TABLE IF EXISTS {table_name};

CREATE TABLE {table_name}(
    {columns_sql}
);
"""

In [21]:
sql_schema_query = generate_create_table_sql("application", application_column_types)
print(sql_schema_query)
db.execute_query(sql_schema_query)

DROP TABLE IF EXISTS application;

CREATE TABLE application(
    SK_ID_CURR INTEGER,
    TARGET SMALLINT,
    NAME_CONTRACT_TYPE VARCHAR(15),
    CODE_GENDER VARCHAR(3),
    FLAG_OWN_CAR VARCHAR(1),
    FLAG_OWN_REALTY VARCHAR(1),
    CNT_CHILDREN SMALLINT,
    AMT_INCOME_TOTAL REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_TYPE_SUITE VARCHAR(15),
    NAME_INCOME_TYPE VARCHAR(20),
    NAME_EDUCATION_TYPE VARCHAR(29),
    NAME_FAMILY_STATUS VARCHAR(20),
    NAME_HOUSING_TYPE VARCHAR(19),
    REGION_POPULATION_RELATIVE REAL,
    DAYS_BIRTH SMALLINT,
    DAYS_EMPLOYED INTEGER,
    DAYS_REGISTRATION REAL,
    DAYS_ID_PUBLISH SMALLINT,
    OWN_CAR_AGE REAL,
    FLAG_MOBIL SMALLINT,
    FLAG_EMP_PHONE SMALLINT,
    FLAG_WORK_PHONE SMALLINT,
    FLAG_CONT_MOBILE SMALLINT,
    FLAG_PHONE SMALLINT,
    FLAG_EMAIL SMALLINT,
    OCCUPATION_TYPE VARCHAR(21),
    CNT_FAM_MEMBERS REAL,
    REGION_RATING_CLIENT SMALLINT,
    REGION_RATING_CLIENT_W_CITY SMALLINT,
    WEEKDAY_APPR_PROCESS_START VARCHAR(9),
    HOUR_APPR_PROCESS_START SMALLINT,
    REG_REGION_NOT_LIVE_REGION SMALLINT,
    REG_REGION_NOT_WORK_REGION SMALLINT,
    LIVE_REGION_NOT_WORK_REGION SMALLINT,
    REG_CITY_NOT_LIVE_CITY SMALLINT,
    REG_CITY_NOT_WORK_CITY SMALLINT,
    LIVE_CITY_NOT_WORK_CITY SMALLINT,
    ORGANIZATION_TYPE VARCHAR(22),
    EXT_SOURCE_1 REAL,
    EXT_SOURCE_2 REAL,
    EXT_SOURCE_3 REAL,
    APARTMENTS_AVG REAL,
    BASEMENTAREA_AVG REAL,
    YEARS_BEGINEXPLUATATION_AVG REAL,
    YEARS_BUILD_AVG REAL,
    COMMONAREA_AVG REAL,
    ELEVATORS_AVG REAL,
    ENTRANCES_AVG REAL,
    FLOORSMAX_AVG REAL,
    FLOORSMIN_AVG REAL,
    LANDAREA_AVG REAL,
    LIVINGAPARTMENTS_AVG REAL,
    LIVINGAREA_AVG REAL,
    NONLIVINGAPARTMENTS_AVG REAL,
    NONLIVINGAREA_AVG REAL,
    APARTMENTS_MODE REAL,
    BASEMENTAREA_MODE REAL,
    YEARS_BEGINEXPLUATATION_MODE REAL,
    YEARS_BUILD_MODE REAL,
    COMMONAREA_MODE REAL,
    ELEVATORS_MODE REAL,
    ENTRANCES_MODE REAL,
    FLOORSMAX_MODE REAL,
    FLOORSMIN_MODE REAL,
    LANDAREA_MODE REAL,
    LIVINGAPARTMENTS_MODE REAL,
    LIVINGAREA_MODE REAL,
    NONLIVINGAPARTMENTS_MODE REAL,
    NONLIVINGAREA_MODE REAL,
    APARTMENTS_MEDI REAL,
    BASEMENTAREA_MEDI REAL,
    YEARS_BEGINEXPLUATATION_MEDI REAL,
    YEARS_BUILD_MEDI REAL,
    COMMONAREA_MEDI REAL,
    ELEVATORS_MEDI REAL,
    ENTRANCES_MEDI REAL,
    FLOORSMAX_MEDI REAL,
    FLOORSMIN_MEDI REAL,
    LANDAREA_MEDI REAL,
    LIVINGAPARTMENTS_MEDI REAL,
    LIVINGAREA_MEDI REAL,
    NONLIVINGAPARTMENTS_MEDI REAL,
    NONLIVINGAREA_MEDI REAL,
    FONDKAPREMONT_MODE VARCHAR(21),
    HOUSETYPE_MODE VARCHAR(16),
    TOTALAREA_MODE REAL,
    WALLSMATERIAL_MODE VARCHAR(12),
    EMERGENCYSTATE_MODE VARCHAR(3),
    OBS_30_CNT_SOCIAL_CIRCLE REAL,
    DEF_30_CNT_SOCIAL_CIRCLE REAL,
    OBS_60_CNT_SOCIAL_CIRCLE REAL,
    DEF_60_CNT_SOCIAL_CIRCLE REAL,
    DAYS_LAST_PHONE_CHANGE REAL,
    FLAG_DOCUMENT_2 SMALLINT,
    FLAG_DOCUMENT_3 SMALLINT,
    FLAG_DOCUMENT_4 SMALLINT,
    FLAG_DOCUMENT_5 SMALLINT,
    FLAG_DOCUMENT_6 SMALLINT,
    FLAG_DOCUMENT_7 SMALLINT,
    FLAG_DOCUMENT_8 SMALLINT,
    FLAG_DOCUMENT_9 SMALLINT,
    FLAG_DOCUMENT_10 SMALLINT,
    FLAG_DOCUMENT_11 SMALLINT,
    FLAG_DOCUMENT_12 SMALLINT,
    FLAG_DOCUMENT_13 SMALLINT,
    FLAG_DOCUMENT_14 SMALLINT,
    FLAG_DOCUMENT_15 SMALLINT,
    FLAG_DOCUMENT_16 SMALLINT,
    FLAG_DOCUMENT_17 SMALLINT,
    FLAG_DOCUMENT_18 SMALLINT,
    FLAG_DOCUMENT_19 SMALLINT,
    FLAG_DOCUMENT_20 SMALLINT,
    FLAG_DOCUMENT_21 SMALLINT,
    AMT_REQ_CREDIT_BUREAU_HOUR REAL,
    AMT_REQ_CREDIT_BUREAU_DAY REAL,
    AMT_REQ_CREDIT_BUREAU_WEEK REAL,
    AMT_REQ_CREDIT_BUREAU_MON REAL,
    AMT_REQ_CREDIT_BUREAU_QRT REAL,
    AMT_REQ_CREDIT_BUREAU_YEAR REAL,
    DATASET_SOURCE VARCHAR(5)
);

Запрос выполнен успешно
Время выполнения: 0:00:00

In [22]:
application_train_columns = [col for col in application_column_types.keys() if col != "DATASET_SOURCE"]

In [23]:
application_test_columns = [
    col for col in application_column_types.keys()
    if col not in ("TARGET", "DATASET_SOURCE")
]

In [24]:
db.execute_query("""
UPDATE application
SET DATASET_SOURCE = 'train'
WHERE DATASET_SOURCE IS NULL AND TARGET IS NOT NULL;
""")

Запрос выполнен успешно
Время выполнения: 0:00:00

In [25]:
application_test_file = Path(DATA_FULL_PATH) / "application_test.csv"

db.copy_from_csv(
    table_name="application",
    file_path=str(application_test_file),
    columns=application_test_columns
)

Данные из application_test.csv успешно загружены в application
Время выполнения: 0:00:00

In [26]:
from pathlib import Path

application_train_file = Path(DATA_FULL_PATH) / "application_train.csv"

db.copy_from_csv(
    table_name="application",
    file_path=str(application_train_file),
    columns=application_train_columns
)

Данные из application_train.csv успешно загружены в application
Время выполнения: 0:00:04

In [27]:
db.execute_query("""
UPDATE application
SET DATASET_SOURCE = 'train'
WHERE DATASET_SOURCE IS NULL AND TARGET IS NOT NULL;
""")

Запрос выполнен успешно
Время выполнения: 0:00:05

In [28]:
db.execute_query("""
UPDATE application
SET DATASET_SOURCE = 'test'
WHERE DATASET_SOURCE IS NULL AND TARGET IS NULL;
""")

Запрос выполнен успешно
Время выполнения: 0:00:04

In [18]:
db.get_df("""
SELECT
    DATASET_SOURCE,
    COUNT(*) AS row_count,
    COUNT(TARGET) AS target_not_null_cnt
FROM application
GROUP BY DATASET_SOURCE
ORDER BY DATASET_SOURCE;
""")

Время выполнения: 0:00:00

  dataset_source  row_count  target_not_null_cnt
0           test      48744                    0
1          train     307511               307511

### Обоснование выбора структуры таблицы `application`

Таблицы `application_train` и `application_test` были объединены в одну таблицу `application`, так как они имеют одинаковую структуру признаков и различаются только наличием целевой переменной `TARGET` в обучающей выборке.

Поле `TARGET` сохранено в таблице `application` как `SMALLINT` и допускает `NULL`, поскольку для строк из `application_test` значения целевой переменной отсутствуют.

Для удобства различения источника записи добавлено поле `DATASET_SOURCE`, принимающее значения `train` и `test`.

Поле `SK_ID_CURR` сохранено как `INTEGER` и используется как основной идентификатор клиента. Его тип согласован с другими таблицами проекта для последующего задания связей.

Столбцы типа `int64` с небольшим диапазоном значений сохранены как `SMALLINT`, а более широкие целочисленные идентификаторы — как `INTEGER`.

Столбцы типа `float64` сохранены как `REAL`, включая те, которые по смыслу являются целочисленными, поскольку в исходных CSV-файлах они представлены в формате чисел с плавающей точкой (`2.0`, `1.0` и т.п.), и это необходимо для корректной прямой загрузки через `COPY`.

Категориальные строковые признаки сохранены как `VARCHAR(N)`, где `N` соответствует максимальной длине значения в столбце.

In [19]:
query = """
    SELECT *
    FROM
        application
    JOIN
        bureau
        ON application.sk_id_curr = bureau.sk_id_curr
    
"""
db.get_df(query)

Время выполнения: 0:01:29

,sk_id_curr,target,name_contract_type,code_gender,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,...,days_enddate_fact,amt_credit_max_overdue,cnt_credit_prolong,amt_credit_sum,amt_credit_sum_debt,amt_credit_sum_limit,amt_credit_sum_overdue,credit_type,days_credit_update,amt_annuity
0,148877,0.0,Cash loans,F,N,Y,0,360000.0,521280.0,26743.5,...,NaN,NaN,0,315000.0,328086.00,NaN,0.0,Credit card,-6,NaN
1,148877,0.0,Cash loans,F,N,Y,0,360000.0,521280.0,26743.5,...,NaN,NaN,0,272520.0,252585.00,0.0,0.0,Consumer credit,-18,9499.500
2,148877,0.0,Cash loans,F,N,Y,0,360000.0,521280.0,26743.5,...,NaN,NaN,0,63427.5,47389.50,0.0,0.0,Consumer credit,-5,37469.387
3,148877,0.0,Cash loans,F,N,Y,0,360000.0,521280.0,26743.5,...,NaN,NaN,0,272520.0,254729.61,NaN,0.0,Consumer credit,-8,9499.500
4,148877,0.0,Cash loans,F,N,Y,0,360000.0,521280.0,26743.5,...,NaN,NaN,0,1836000.0,408431.12,NaN,0.0,Consumer credit,-8,9499.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,453509,NaN,Cash loans,M,Y,Y,0,144000.0,906660.0,36531.0,...,-1620.0,0.0,0,33840.0,0.00,0.0,0.0,Consumer credit,-1620,NaN
1716424,453509,NaN,Cash loans,M,Y,Y,0,144000.0,906660.0,36531.0,...,-348.0,NaN,0,171000.0,0.00,0.0,0.0,Credit card,-345,0.000
1716425,453556,NaN,Cash loans,F,N,Y,0,157500.0,156384.0,16155.0,...,-1631.0,0.0,0,90000.0,NaN,NaN,0.0,Consumer credit,-1630,NaN
1716426,453556,NaN,Cash loans,F,N,Y,0,157500.0,156384.0,16155.0,...,-1098.0,NaN,0,314505.0,0.00,0.0,0.0,Consumer credit,-1079,0.000
1716427,453556,NaN,Cash loans,F,N,Y,0,157500.0,156384.0,16155.0,...,NaN,NaN,0,22500.0,0.00,0.0,0.0,Credit card,-36,0.000

In [20]:
query = """
SELECT 
    application.sk_id_curr, 
    code_gender, 
    sk_id_bureau, 
    amt_credit_sum
FROM 
    application
JOIN
    bureau
    ON
    application.sk_id_curr = bureau.sk_id_curr
"""
db.get_df(query)

Время выполнения: 0:00:03

         sk_id_curr code_gender  sk_id_bureau  amt_credit_sum
0            215354           F       5714462        91323.00
1            215354           F       5714463       225000.00
2            215354           F       5714464       464323.50
3            215354           F       5714465        90000.00
4            215354           F       5714466      2700000.00
...             ...         ...           ...             ...
1716423      318662           F       5057561       147150.00
1716424      145715           F       5057569        35032.50
1716425      317217           F       5057684        93955.50
1716426      352790           M       5057718        28248.84
1716427      352790           M       5057725        27000.00

[1716428 rows x 4 columns]

In [21]:
query = """
SELECT
    app.sk_id_curr,
    app.code_gender,
    bureau_new.count_loans_bki_history,
    bureau_new.loans_sum
FROM application AS app
JOIN (
    SELECT
        sk_id_curr,
        COUNT(sk_id_bureau) AS count_loans_bki_history,
        SUM(amt_credit_sum) AS loans_sum
    FROM bureau
    GROUP BY sk_id_curr
) AS bureau_new
    ON app.sk_id_curr = bureau_new.sk_id_curr
"""
db.get_df(query)

Время выполнения: 0:00:01

        sk_id_curr code_gender  count_loans_bki_history  loans_sum
0           104120           F                        2   378000.0
1           107395           F                        3   333000.0
2           119861           F                        5   899878.5
3           126553           F                       20  4428844.0
4           128433           F                        6   782176.5
...            ...         ...                      ...        ...
305806      456168           F                        2  1962000.0
305807      456170           F                        3   361381.5
305808      456189           F                        6  1905309.0
305809      456223           F                        5  2156309.5
305810      456224           M                       17  3848684.2

[305811 rows x 4 columns]

### Назначение ключей и индексов

In [5]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SK_ID_CURR) AS distinct_sk_id_curr
FROM application;
"""
db.get_df(query)

Время выполнения: 0:00:01

   total_rows  distinct_sk_id_curr
0      356255               356255

In [6]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SK_ID_BUREAU) AS distinct_sk_id_bureau
FROM bureau;
"""
db.get_df(query)

Время выполнения: 0:00:00

   total_rows  distinct_sk_id_bureau
0     1716428                1716428

In [7]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT SK_ID_PREV) AS distinct_sk_id_prev
FROM previous_application;
"""
db.get_df(query)

Время выполнения: 0:00:00

   total_rows  distinct_sk_id_prev
0     1670214              1670214

In [8]:
query = """
SELECT COUNT(*) AS duplicate_cnt
FROM (
    SELECT SK_ID_BUREAU, MONTHS_BALANCE, COUNT(*)
    FROM bureau_balance
    GROUP BY SK_ID_BUREAU, MONTHS_BALANCE
    HAVING COUNT(*) > 1
) t;
"""
db.get_df(query)

Время выполнения: 0:00:31

   duplicate_cnt
0              0

In [9]:
query = """
SELECT COUNT(*) AS duplicate_cnt
FROM (
    SELECT SK_ID_PREV, MONTHS_BALANCE, COUNT(*)
    FROM pos_cash_balance
    GROUP BY SK_ID_PREV, MONTHS_BALANCE
    HAVING COUNT(*) > 1
) t;
"""
db.get_df(query)

Время выполнения: 0:00:07

   duplicate_cnt
0              0

In [10]:
query = """
SELECT COUNT(*) AS duplicate_cnt
FROM (
    SELECT SK_ID_PREV, MONTHS_BALANCE, COUNT(*)
    FROM credit_card_balance
    GROUP BY SK_ID_PREV, MONTHS_BALANCE
    HAVING COUNT(*) > 1
) t;
"""
db.get_df(query)

Время выполнения: 0:00:03

   duplicate_cnt
0              0

In [11]:
query = """
SELECT COUNT(*) AS duplicate_cnt
FROM (
    SELECT
        SK_ID_PREV,
        NUM_INSTALMENT_NUMBER,
        DAYS_INSTALMENT,
        COUNT(*)
    FROM installments_payments
    GROUP BY
        SK_ID_PREV,
        NUM_INSTALMENT_NUMBER,
        DAYS_INSTALMENT
    HAVING COUNT(*) > 1
) t;
"""
db.get_df(query)

Время выполнения: 0:00:13

   duplicate_cnt
0         730392

Если есть дубликаты, лучше не делать PK, а оставить только индексы.

In [ ]:
query = """
ALTER TABLE application
ADD CONSTRAINT pk_application
PRIMARY KEY (SK_ID_CURR);
"""
db.execute_query(query)

In [16]:
query = """
ALTER TABLE bureau
ADD CONSTRAINT pk_bureau
PRIMARY KEY (SK_ID_BUREAU);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [17]:
query = """
ALTER TABLE previous_application
ADD CONSTRAINT pk_previous_application
PRIMARY KEY (SK_ID_PREV);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:01

In [18]:
query = """
ALTER TABLE bureau_balance
ADD CONSTRAINT pk_bureau_balance
PRIMARY KEY (SK_ID_BUREAU, MONTHS_BALANCE);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:21

In [19]:
query = """
ALTER TABLE pos_cash_balance
ADD CONSTRAINT pk_pos_cash_balance
PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:06

In [20]:
query = """
ALTER TABLE credit_card_balance
ADD CONSTRAINT pk_credit_card_balance
PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:03

In [27]:
query = """
ALTER TABLE bureau
ADD CONSTRAINT fk_bureau_application
FOREIGN KEY (SK_ID_CURR) REFERENCES application(SK_ID_CURR);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:00

In [ ]:
query = """
ALTER TABLE previous_application
ADD CONSTRAINT fk_previous_application_application
FOREIGN KEY (SK_ID_CURR) REFERENCES application(SK_ID_CURR);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:00

### Проверка внешних ключей

Перед назначением внешних ключей была выполнена проверка ссылочной целостности между дочерними и родительскими таблицами.

Для связей:
- `bureau.SK_ID_CURR -> application.SK_ID_CURR`
- `previous_application.SK_ID_CURR -> application.SK_ID_CURR`

нарушений не обнаружено, поэтому внешние ключи были добавлены.

Для связей:
- `pos_cash_balance.SK_ID_PREV -> previous_application.SK_ID_PREV`
- `credit_card_balance.SK_ID_PREV -> previous_application.SK_ID_PREV`
- `installments_payments.SK_ID_PREV -> previous_application.SK_ID_PREV`
- `bureau_balance.SK_ID_BUREAU -> bureau.SK_ID_BUREAU`

были обнаружены значения `SK_ID_PREV`, отсутствующие в таблице `previous_application`. Поэтому внешние ключи для этих связей не назначались. Вместо этого были созданы индексы по соответствующим полям для ускорения соединений таблиц.

In [34]:
query = """
CREATE INDEX IF NOT EXISTS idx_pos_cash_balance_sk_id_prev
ON pos_cash_balance(SK_ID_PREV);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:04

In [35]:
query = """
CREATE INDEX IF NOT EXISTS idx_credit_card_balance_sk_id_prev
ON credit_card_balance(SK_ID_PREV);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:01

In [36]:
query = """
CREATE INDEX IF NOT EXISTS idx_installments_payments_sk_id_prev
ON installments_payments(SK_ID_PREV);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:06

In [37]:
query = """
CREATE INDEX IF NOT EXISTS idx_bureau_balance_sk_id_bureau
ON bureau_balance(SK_ID_BUREAU);
"""
db.execute_query(query)

Запрос выполнен успешно
Время выполнения: 0:00:11